### ISSUE TITLE
docker-compose 

### ISSUE THREAD

**Issue by jallphin** [target/attack-navigator-docker#7]
**Is your feature request related to a problem? Please describe.**
Use docker-compose instead of make files

**Describe the solution you'd like**
Use or adapt below docker-compose file

**Describe alternatives you've considered**
docker-compose is nice and tidy 

**Additional context**
```
version: '3'
services:
  attack-nav-node:
    image: node:16
    container_name: attack-nav-node
    volumes:
      - ./attack-navigator:/attack-navigator
    command: sh -c "cd /attack-navigator/nav-app && npm install -g @angular/cli && npm install --unsafe-perm && ng build"
  attack-nav-web:
    container_name: attack-nav-web
    depends_on:
      - attack-nav-node
    image: nginx:stable-alpine
    ports:
      - 8080:80
    volumes:
      - ./attack-navigator/nav-app/dist:/usr/share/nginx/html
  ```
